// ─────────────────────────────────────────────────────────────────────────────
// scripts/build.mjs — wrap src/client.js into the dsh-client-modules factory form
// ─────────────────────────────────────────────────────────────────────────────
// Output contract (must match what @deepseek-ai/dsh-client-modules serves):
//   window.__ModuleLoader__.load({ id, factory: (require) => { ... } })
// The factory body is a lazy-CJS module: `require` resolves externalized deps
// (here only `react`), and the body returns module.exports. src/client.js is the
// factory INTERIOR, so this step is pure wrapping — no transpilation.
//
// To move to TSX/TS later, replace this script with a bundler (tsdown/esbuild)
// that emits this same shape: an IIFE registering via window.__ModuleLoader__.load,
// with `react` kept external (resolved by `require` at materialization).
// ─────────────────────────────────────────────────────────────────────────────
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname } from "node:path";

const here = dirname(fileURLToPath(import.meta.url)); // .../scripts
const root = dirname(here);                            // .../dsh-plugin-pet
const pkg = JSON.parse(readFileSync(`${root}/package.json`, "utf8"));
const id = pkg.name;
const body = readFileSync(`${root}/src/client.js`, "utf8").replace(/\s+$/, "");
const indented = body.split("\n").map((line) => "\t\t" + line).join("\n");

const out = `// AUTO-GENERATED by \`npm run build\` (scripts/build.mjs).
// Source: src/client.js — edit there, then rebuild. Do not edit this file by hand.
window.__ModuleLoader__.load({
\tid: ${JSON.stringify(id)},
\tfactory: (require) => {
\t\tvar module = { exports: {} };
\t\tvar exports = module.exports;
\t\tObject.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
${indented}
\t\treturn module.exports;
\t}
});
`;

writeFileSync(`${root}/lib/client.js`, out);
console.log(`built lib/client.js (${out.length} bytes) from src/client.js — mount via ${/MOUNT\s*=\s*"([^"]+)"/.exec(body)?.[1] ?? "?"}`);
