// ─────────────────────────────────────────────────────────────────────────────
// scripts/build.mjs — wrap src/client.js into the dsh-client-modules factory form
// ─────────────────────────────────────────────────────────────────────────────
// Output contract (must match what @deepseek-ai/dsh-client-modules serves):
//   window.__ModuleLoader__.load({ id, factory: (require) => { ... } })
// The factory body is a lazy-CJS module: `require` resolves externalized deps
// (here only `react`), and the body returns module.exports. src/client.js is the
// factory INTERIOR, so this step is pure wrapping — no transpilation.
//
// To move to TSX/TS later, replace this script with a bundler (tsdown/esbuild)
// that emits this same shape: an IIFE registering via window.__ModuleLoader__.load,
// with `react` kept external (resolved by `require` at materialization).
//
// The wrap/build functions are exported so scripts/check.mjs can validate the
// output without re-implementing the wrapping logic.
// ─────────────────────────────────────────────────────────────────────────────
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath, pathToFileURL } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url)); // .../scripts
const root = dirname(here);                            // .../dsh-plugin-pet

export function readPkg() {
	return JSON.parse(readFileSync(join(root, "package.json"), "utf8"));
}

export function readSource() {
	return readFileSync(join(root, "src/client.js"), "utf8").replace(/\s+$/, "");
}

export function wrapBody(body, id) {
	const indented = body.split("\n").map((line) => "\t\t" + line).join("\n");
	return `// AUTO-GENERATED by \`npm run build\` (scripts/build.mjs).
// Source: src/client.js — edit there, then rebuild. Do not edit this file by hand.
window.__ModuleLoader__.load({
\tid: ${JSON.stringify(id)},
\tfactory: (require) => {
\t\tvar module = { exports: {} };
\t\tvar exports = module.exports;
\t\tObject.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
${indented}
\t\treturn module.exports;
\t}
});
`;
}

export function build() {
	const pkg = readPkg();
	const body = readSource();
	const out = wrapBody(body, pkg.name);
	writeFileSync(join(root, "lib/client.js"), out);
	const mount = /MOUNT\s*=\s*"([^"]+)"/.exec(body)?.[1] ?? "?";
	return { out, id: pkg.name, mount, version: pkg.version };
}

// Run only when invoked directly (not when imported by scripts/check.mjs).
const isMain = process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href;
if (isMain) {
	const r = build();
	console.log(`built lib/client.js (${(r.out.length / 1024).toFixed(1)} KiB) from src/client.js — v${r.version} · mount=${r.mount}`);
}
